const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function plusDays(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
const foodPhotos={"Lait demi-écrémé":"https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=600&q=80","Œufs":"https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=600&q=80","Tomates":"https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80","Brocoli":"https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&q=80","Riz basmati":"https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80","Pain complet":"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80","Yaourt nature":"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80"};
const recipePhotos=["https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80"];
const defaultState={inventory:[{name:"Lait demi-écrémé",qty:"1 L",zone:"Frigo",expiry:plusDays(2),owner:"Kevin"},{name:"Œufs",qty:"12 unités",zone:"Frigo",expiry:plusDays(5),owner:"Jean Jacques"},{name:"Tomates",qty:"500 g",zone:"Frigo",expiry:plusDays(1),owner:"Hafedh"},{name:"Brocoli",qty:"1 tête",zone:"Frigo",expiry:plusDays(4),owner:"Danensky"},{name:"Riz basmati",qty:"1 kg",zone:"Garde-manger",expiry:plusDays(30),owner:"Hafedh"},{name:"Yaourt nature",qty:"4 pots",zone:"Frigo",expiry:plusDays(6),owner:"Kevin"}],shopping:[{item:"Oignons",member:"Hafedh",done:false},{item:"Ail",member:"Kevin",done:false},{item:"Citron",member:"Jean Jacques",done:true},{item:"Pâtes complètes",member:"Danensky",done:false}],members:[{name:"Hafedh Dekhil",role:"Backend / base de données",initial:"H"},{name:"Jean Jacques Arquero",role:"Frontend / UI",initial:"J"},{name:"Kevin Mai",role:"Collaboration / groupe",initial:"K"},{name:"Danensky",role:"DevOps / tests",initial:"D"}]};
const recipes=[{title:"Pâtes aux légumes",time:"20 min",impact:"Avec vos restes",needs:["Oignons","Ail"],uses:["Tomates","Brocoli"],img:recipePhotos[0]},{title:"Omelette au brocoli",time:"15 min",impact:"Rapide et protéiné",needs:["Fromage"],uses:["Œufs","Brocoli"],img:recipePhotos[1]},{title:"Soupe anti-gaspi",time:"25 min",impact:"Réduit les pertes",needs:["Bouillon"],uses:["Tomates","Pain complet"],img:recipePhotos[2]}];
let state=load();let scanIndex=0;let detected=null;const scans=[{name:"Lait demi-écrémé",qty:"1 L",zone:"Frigo",expiry:plusDays(2),img:foodPhotos["Lait demi-écrémé"],tags:["Produit laitier","Expire bientôt","Frigo"]},{name:"Tomates",qty:"500 g",zone:"Frigo",expiry:plusDays(1),img:foodPhotos["Tomates"],tags:["Légume","À utiliser","Recette possible"]},{name:"Œufs",qty:"12 unités",zone:"Frigo",expiry:plusDays(5),img:foodPhotos["Œufs"],tags:["Protéine","Disponible","Validation OK"]}];
function load(){try{return JSON.parse(localStorage.getItem("mealsaver-commercial-v4"))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}function save(){localStorage.setItem("mealsaver-commercial-v4",JSON.stringify(state))}function daysLeft(dateStr){const t=new Date();t.setHours(0,0,0,0);return Math.ceil((new Date(dateStr+"T00:00:00")-t)/86400000)}function statusFor(d){const n=daysLeft(d);if(n<=1)return[`Expire ${n===1?"demain":"aujourd’hui"}`,"urgent"];if(n<=3)return[`Expire dans ${n} jours`,"urgent"];return[`Expire dans ${n} jours`,"ok"]}function foodImg(n){return foodPhotos[n]||"https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80"}
function switchScreen(id){$$('.app-screen').forEach(s=>s.classList.toggle('active-screen',s.id===id));$$('.app-nav').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));const titles={dash:"Bonjour famille Durand 👋",inventory:"Inventaire du foyer",scan:"Scan intelligent MVP",recipes:"Recettes anti-gaspillage",list:"Liste collaborative",group:"Foyer collaboratif"};const title=$('#app-title');if(title)title.textContent=titles[id]||"MealSaver"}
function renderRecipes(target){const html=recipes.map(r=>`<article class="recipe-item"><img src="${r.img}" alt="${r.title}"><div><h4>${r.title}</h4><small>⏱ ${r.time} · ${r.impact}</small><p><b>Utilise :</b> ${r.uses.join(', ')}</p><button class="btn btn-soft add-needs" data-needs="${r.needs.join('|')}">Ajouter les manquants</button></div></article>`).join('');if($(target))$(target).innerHTML=html}
function renderInventory(){if(!$('#inventoryList'))return;$('#inventoryList').innerHTML=state.inventory.map((f,i)=>{const [txt,cls]=statusFor(f.expiry);return`<article class="food-row"><div class="food-left"><img src="${foodImg(f.name)}" alt="${f.name}"><div><strong>${f.name}</strong><small>${f.qty} · ${f.zone} · ajouté par ${f.owner}</small></div></div><div><span class="status ${cls}">${txt}</span><button class="text-link remove-food" data-i="${i}">Retirer</button></div></article>`}).join('')}
function renderAlerts(){const list=state.inventory.filter(f=>daysLeft(f.expiry)<=3).sort((a,b)=>daysLeft(a.expiry)-daysLeft(b.expiry));const html=list.map(f=>`<article class="alert-row"><div class="food-left"><img src="${foodImg(f.name)}" alt="${f.name}"><div><strong>${f.name}</strong><small>${statusFor(f.expiry)[0]} · ${f.qty}</small></div></div><span class="status urgent">Priorité</span></article>`).join('');if($('#dashAlerts'))$('#dashAlerts').innerHTML=html||'<p>Aucune alerte critique.</p>'}
function renderShopping(){if(!$('#shoppingList'))return;$('#shoppingList').innerHTML=state.shopping.map((s,i)=>`<article class="shop-row ${s.done?'done':''}"><div class="food-left"><button class="check toggle-shop" data-i="${i}">${s.done?'✓':''}</button><div><strong>${s.item}</strong><small>Assigné à ${s.member}</small></div></div><button class="text-link remove-shop" data-i="${i}">Retirer</button></article>`).join('')}
function renderMembers(){if(!$('#memberGrid'))return;$('#memberGrid').innerHTML=state.members.map(m=>`<article class="member"><b>${m.initial}</b><h3>${m.name}</h3><p>${m.role}</p></article>`).join('')}
function renderAll(){renderRecipes('#dashRecipes');renderRecipes('#recipeList');renderInventory();renderAlerts();renderShopping();renderMembers()}
function initApp(){if(!document.body.classList.contains('app-body'))return;renderAll();document.addEventListener('click',e=>{const nav=e.target.closest('[data-screen]');if(nav)switchScreen(nav.dataset.screen);const rf=e.target.closest('.remove-food');if(rf){state.inventory.splice(+rf.dataset.i,1);save();renderAll()}const rs=e.target.closest('.remove-shop');if(rs){state.shopping.splice(+rs.dataset.i,1);save();renderShopping()}const ts=e.target.closest('.toggle-shop');if(ts){state.shopping[+ts.dataset.i].done=!state.shopping[+ts.dataset.i].done;save();renderShopping()}const needs=e.target.closest('.add-needs');if(needs){needs.dataset.needs.split('|').forEach(item=>{if(!state.shopping.some(s=>s.item.toLowerCase()===item.toLowerCase()))state.shopping.push({item,member:'Kevin',done:false})});save();renderShopping();switchScreen('list')}});$('#foodForm')?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.inventory.unshift({...d,owner:'Hafedh'});e.target.reset();save();renderAll()});$('#shoppingForm')?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.shopping.unshift({item:d.item,member:d.member,done:false});e.target.reset();save();renderShopping()});$('#changeScan')?.addEventListener('click',()=>{scanIndex=(scanIndex+1)%scans.length;$('#scanImg').src=scans[scanIndex].img;detected=null;$('#detectedTitle').textContent='En attente d’analyse';$('#detectedMeta').textContent='Photo ou téléversement → détection → validation utilisateur → inventaire.';$('#detectedTags').innerHTML='';$('#addDetected').disabled=true});$('#analyzeScan')?.addEventListener('click',()=>{detected=scans[scanIndex];$('#detectedTitle').textContent=detected.name;$('#detectedMeta').textContent=`${detected.qty} · ${detected.zone} · expiration estimée : ${detected.expiry}`;$('#detectedTags').innerHTML=detected.tags.map(t=>`<span>${t}</span>`).join('');$('#addDetected').disabled=false});$('#addDetected')?.addEventListener('click',()=>{if(!detected)return;state.inventory.unshift({name:detected.name,qty:detected.qty,zone:detected.zone,expiry:detected.expiry,owner:'Scan'});save();renderAll();switchScreen('inventory')});$('#quickAdd')?.addEventListener('click',()=>switchScreen('inventory'))}
function initLanding(){if(document.body.classList.contains('app-body'))return;const toggle=$('.menu-toggle');toggle?.addEventListener('click',()=>{document.querySelector('.desktop-nav')?.classList.toggle('open')})}
initLanding();initApp();
